### ISSUE TITLE
Publish Outliner to PyPI

### ISSUE THREAD

**Issue by LucasAndradeDias** [LucasAndradeDias/outliner#7]
### Task Checklist
**Goal**:
The goal of this issue is to publish our [Library Name] to PyPI, making it easily accessible to users and allowing them to install it via pip.

**Description**:
Publishing a library to PyPI involves several steps to create distribution packages and upload them to the PyPI repository. In this issue, we will outline the necessary steps to successfully publish our Python library to PyPI.

1. **Prepare the Library**:
   - [ ] Ensure that the library code is stable and ready for release.
   - [ ] Update the library's version number in the appropriate files (e.g., `setup.py` or `pyproject.toml`).
   - [ ] Include a `README` file with usage instructions and documentation.
   - [ ] Ensure that all required dependencies are listed in the project configuration (e.g., `requirements.txt`).

2. **Create Distribution Packages**:
   - [ ] Build distribution packages using a tool like `setuptools` or `flit`.
   - [ ] Test the distribution packages locally to ensure they work correctly.

3. **Create a PyPI Account**:
   - [ ] If you don't have one, create an account on the [PyPI website](https://pypi.org/account/register/).

4. **Configure PyPI Credentials**:
   - [ ] Set up your PyPI credentials by creating a `~/.pypirc` or `pyproject.toml` file with your PyPI username and password (or API token).

5. **Upload the Packages**:
   - [ ] Use a tool like `twine` to upload the distribution packages to PyPI. You can use the following command:
     ```bash
     twine upload dist/*
     ```
     Ensure that you are in the correct virtual environment and directory containing the distribution packages.

6. **Test the Published Package**:
   - [ ] Create a new virtual environment and install the library using pip:
     ```bash
     pip install your-library-name
     ```
   - [ ] Verify that the library works as expected.

7. **Update Documentation**:
   - [ ] Update the library's documentation (e.g., README) to include installation and usage instructions for users.

8. **Announce the Release**:
   - [ ] Announce the release of the library on relevant platforms, forums, and social media to increase its visibility.
